name: docs_pages_workflow

# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ main ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: System update
        run: |
          apt-get update
          apt-get install -y build-essential git

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
          pwd
          ls -hal

      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        shell: bash

      - name: Execute script to build the handbook and update gh-pages.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./gh-build.sh"
        shell: bash
