name: docs_pages_workflow

# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ main ]

jobs:
  build_handbook:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: System update
        run: |
          apt-get update
          apt-get install -y build-essential git python3 python3-pip python3-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Python version
        run: |
          python3 -c "import sys; print(sys.version)"
          pwd
          ls -hal

      - name: Python dependencies
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install -r requirements.txt
        shell: bash

      - name: Execute script to build the handbook and update gh-pages.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./gh-build.sh"
        shell: bash
