name: docs_pages_workflow

# execute this workflow automatically when a we push to main
on:
  push:
    branches: [ main ]

jobs:
  build_handbook:
    runs-on: ubuntu-latest
    container: python:3-slim

    steps:
      - name: System update
        run: |
          apt-get update
          apt-get install -y build-essential git

      - name: Checkout
        uses: actions/checkout@v3

      - run: git config --global --add safe.directory /__w/handbook/handbook

      - name: Python dependencies
        run: pip install -r requirements.txt

      - name: Execute script to build the handbook and update gh-pages.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./gh-build.sh"
        shell: bash
